### PR TITLE
Fix build on i386_HOST_ARCH

### LINKED ISSUE #452: Does not build on 32bit
```
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - streamly-0.7.1 (lib:streamly) (first run)
Configuring streamly-0.7.1...
checking for gcc... /usr/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /usr/bin/gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for clock_gettime... yes
configure: creating ./config.status
config.status: creating src/Streamly/Internal/Data/Time/config.h
Preprocessing library for streamly-0.7.1..
Building library for streamly-0.7.1..
[ 1 of 68] Compiling Streamly.FileSystem.IOVec ( /root/streamly/dist-newstyle/build/i386-linux/ghc-8.6.5/streamly-0.7.1/build/Streamly/FileSystem/IOVec.hs, /root/streamly/dist-newstyle/build/i386-linux/ghc-8.6.5/streamly-0.7.1/build/Streamly/FileSystem/IOVec.o )

src/Streamly/FileSystem/IOVec.hsc:55:15: error:
    Not in scope: type constructor or class ‘Word32’
    Perhaps you meant one of these:
      ‘Word’ (imported from Prelude), ‘Word8’ (imported from Data.Word),
      ‘Word64’ (imported from Data.Word)
    Perhaps you want to add ‘Word32’ to the import list
    in the import of ‘Data.Word’
    (src/Streamly/FileSystem/IOVec.hsc:25:1-32).
   |
55 |       len  :: #{type size_t} <- #{peek struct iovec, iov_len}  ptr
   |               ^^^^^^

src/Streamly/FileSystem/IOVec.hsc:59:19: error:
    Not in scope: type constructor or class ‘Word32’
    Perhaps you meant one of these:
      ‘Word’ (imported from Prelude), ‘Word8’ (imported from Data.Word),
      ‘Word64’ (imported from Data.Word)
    Perhaps you want to add ‘Word32’ to the import list
    in the import of ‘Data.Word’
    (src/Streamly/FileSystem/IOVec.hsc:25:1-32).
   |
59 |           len  :: #{type size_t} = iovLen  vec
   |                   ^^^^^^
```

### PR DESCRIPTION
**Pull request by hasufell**
Fixes #452

### CODE REVIEW

File: src/Streamly/Internal/Data/Fold.hs [hunk 1]
```diff
@@ -556,17 +556,17 @@ stdDev = sqrt variance
 --
 -- @since 0.7.0
 {-# INLINABLE rollingHashWithSalt #-}
-rollingHashWithSalt :: (Monad m, Enum a) => Int -> Fold m a Int
+rollingHashWithSalt :: (Monad m, Enum a) => Integer -> Fold m a Integer
 rollingHashWithSalt salt = Fold step initial extract
     where
-    k = 2891336453
+    k = 2891336453 :: Integer
```
Comment (hasufell) [inline src/Streamly/Internal/Data/Fold.hs]: This is outside of 32bit Int, so I converted all to Integer. Not sure that has any impact.

File: src/Streamly/Internal/Data/Fold.hs [hunk 2]
```diff
@@ -556,17 +556,17 @@ stdDev = sqrt variance
...
     initial = return salt
-    step cksum a = return $ cksum * k + fromEnum a
+    step cksum a = return $ cksum * k + fromIntegral (fromEnum a)
```
Comment (hasufell) [inline src/Streamly/Internal/Data/Fold.hs]: This is an upcast, so should be safe.

File: src/Streamly/FileSystem/IOVec.hsc [hunk 3]
```diff
@@ -53,10 +56,20 @@ instance Storable IOVec where
   peek ptr = do
       base <- #{peek struct iovec, iov_base} ptr
       len  :: #{type size_t} <- #{peek struct iovec, iov_len}  ptr
-      return $ IOVec base len
+      return $ IOVec base
+#if defined(i386_HOST_ARCH)
+               (fromIntegral len)
```
Comment (hasufell) [inline src/Streamly/FileSystem/IOVec.hsc]: I'm not sure these are correct. The error is:

> Couldn't match expected type Word32 with actual type Word64.

So we are downcasting.

File: src/Streamly/FileSystem/IOVec.hsc [hunk 4]
```diff
@@ -53,10 +56,20 @@ instance Storable IOVec where
...
+#else
+               len
+#endif
   poke ptr vec = do
       let base = iovBase vec
-          len  :: #{type size_t} = iovLen  vec
+          len  :: #{type size_t} =
+#if defined(i386_HOST_ARCH)
+            fromIntegral (iovLen vec)
```
Comment (hasufell) [inline src/Streamly/FileSystem/IOVec.hsc]: Error was

> Couldn't match expected type Word32 with actual type Word64.

Doesn't seem to safe?

File: src/Streamly/Internal/Data/Fold.hs (hunk 1 above)
Comment (harendra-kumar) [reply src/Streamly/Internal/Data/Fold.hs]: Integer would make it too slow. We can use `Int64` instead.

File: src/Streamly/Internal/Data/Fold.hs [hunk 5]
```diff
@@ -556,17 +556,17 @@ stdDev = sqrt variance
...
     extract = return
 
 -- | A default salt used in the implementation of 'rollingHash'.
 {-# INLINE defaultSalt #-}
-defaultSalt :: Int
+defaultSalt :: Integer
 #if WORD_SIZE_IN_BITS == 64
```
Comment (harendra-kumar) [inline src/Streamly/Internal/Data/Fold.hs]: I guess this can be removed if we use `Int64` type here. @adithyaov

Comment (hasufell) [reply src/Streamly/Internal/Data/Fold.hs]: `WORD_SIZE_IN_BITS` is undefined on my 64bit machine... what's going on here.

Comment (hasufell) [reply src/Streamly/Internal/Data/Fold.hs]: And it doesn't work:

```
src/Streamly/Internal/Data/Fold.hs:571:15: warning: [-Woverflowed-literals]
    Literal 15868100553162883236 is out of the Int64 range -9223372036854775808..9223372036854775807
    |
571 | defaultSalt = 0xdc36d1615b7400a4
```

Comment (harendra-kumar) [reply src/Streamly/Internal/Data/Fold.hs]: I am not sure where that conditional came from, it probably remained undefined all the time.

Comment (hasufell) [reply src/Streamly/Internal/Data/Fold.hs]: Yes, and the default salt doesn't fit into Int64.

Comment (harendra-kumar) [reply src/Streamly/Internal/Data/Fold.hs]: 0xdc36d1615b7400a4 is not correct, it should be a negative int value of (-2578643520546668380). If we write that in Hex it turns out to be 0xdc36d1615b7400a4 because of the sign bit. So the correct code here will be:

```
defaultSalt = -2578643520546668380
```

Comment (hasufell) [reply src/Streamly/Internal/Data/Fold.hs]: Done

**Comment by harendra-kumar** [comment]
Can you try adding one more build to .travis.yml build matrix with:

```
      arch: x86
```

I think azure pipelines and appveyor CI also support 32-bit linux build.

If we do not add a CI I am pretty sure we will break it very soon.

File: examples/WordClassifier.hs [hunk 6]
```diff
@@ -27,9 +27,9 @@ import qualified Streamly.Prelude as S
 import           System.Environment (getArgs)
 
 instance (Enum a, Storable a) => Hashable (A.Array a) where
-    hash arr = runIdentity $ IUF.fold A.read IFL.rollingHash arr
-    hashWithSalt salt arr = runIdentity $
-        IUF.fold A.read (IFL.rollingHashWithSalt salt) arr
+    hash arr = fromIntegral $ runIdentity $ IUF.fold A.read IFL.rollingHash arr
```
Comment (hasufell) [inline examples/WordClassifier.hs]: The Int64 now created this odd incompatibility with Hashable class. Not sure if that's a problem.

**Comment by hasufell** [comment]
Seems builds have passed.

**Comment by hasufell** [comment]
done

**Comment by harendra-kumar** [comment]
Thanks @hasufell !
