### PR TITLE
fix: Zip/AsyncZip applicative instances

### LINKED ISSUE #34: Equivalent code producing different output
I have found that two equivalent codes are producing different output.
* the first **flow** will produce `[(1, 1), (2, 2), (3, 3)]`
* while **the second** one will produce a single tuple `[(1, 1)]`

Maybe I am stupid but I can't find the answer to this behavior... ?

Example:
```haskell
import           Control.Monad    (join)
import           Streamly
import qualified Streamly.Prelude as S

main = mapM_ print $ join (S.toList . zipping $ flow)
  where
    flow = (,) <$> stream <*> stream
    -- flow = pure (,) <*> stream <*> stream
    stream = S.each [1, 2, 3]
```

### PR DESCRIPTION
**Pull request by hussein-aitlahcen**
This PR fixes #34 by correcting Zip and AsyncZip applicative instances.

### CODE REVIEW

File: src/Streamly/Streams.hs [hunk 1]
```diff
@@ -751,7 +751,7 @@ instance Monad m => Functor (ZipStream m) where
         in m Nothing stp yield
 
 instance Monad m => Applicative (ZipStream m) where
-    pure a = ZipStream $ scons a Nothing
+    pure a = ZipStream $ let x = scons a (Just x) in x
```
Comment (harendra-kumar) [inline src/Streamly/Streams.hs]: it may be a good idea to factor out this pattern in a function called `srepeat` that will construct a stream by repeating a pure element just like `scons` constructs a singleton stream, and use `srepeat` at both these places. You can put that function next to `scons` definition.

**Comment by harendra-kumar** [comment]
@hussein-aitlahcen thanks for finding and quickly fixing it as well! Can you also add a changelog entry in `Changelog.md`? Make a section called `Unreleased` on top and put it under that as a bug fix entry.

**Comment by hussein-aitlahcen** [comment]
@harendra-kumar I just edited the code to make it pointfree since it's trivial. Will add the `Changelog.md` section.

**Comment by hussein-aitlahcen** [comment]
@harendra-kumar made the final changes

**Comment by hussein-aitlahcen** [comment]
Is this okay ?

**Comment by harendra-kumar** [comment]
Merged, thanks again and looking to forward to more from you :-)

**Comment by harendra-kumar** [comment]
Merged, thanks again and looking to forward to more from you :-)
